### ISSUE TITLE
CertificateBindingConfiguration::Bind returns false even if a new binding is created

### ISSUE THREAD

**Issue by wiggisser** [segor/SslCertBinding.Net#6]
I Use the follwing code to replace the binding of an old/invalidated certificate to a port:

    ICertificateBindingConfiguration config = new CertificateBindingConfiguration();
    var ip = new IPEndPoint(IPAddress.Parse("0.0.0.0"), port);
    var cb = config.Query(ip);
    if (cb.Length > 0)
    {
        if (cb[0].Thumbprint.Equals(thumbprint, StringComparison.InvariantCultureIgnoreCase)) 
            return true;
        config.Delete(ip);
    }
    return config.Bind(new CertificateBinding(thumbprint, StoreName.My, ip, APPID));

but `config.Bind(...)` returns `false` even when a new Binding was created. 

My current workaround is querying again after the bind and return `true` if a binding was found.

**Comment by segor** [comment]
Currently `Bind()` adds new record for a port if it does not exist or replaces it.

So instead of all of your code just write  `config.Bind(new CertificateBinding(thumbprint, StoreName.My, ip, APPID))`. It will return false if a new record has been added or true if a record has been updated (replaced). If operation was unsuccessful an exception will be thrown.

**Comment by segor** [comment]
Bind returns false  if a new binding is created by design. Use exception catching to check possible errors.
